import { useLocation, useNavigate } from 'react-router-dom';
import AppShell from '../components/layout/AppShell';
import ErrorState from '../components/shared/ErrorState';
import RiskBadge from '../components/shared/RiskBadge';
import PageTransition from '../components/shared/PageTransition';
import { motion } from 'motion/react';
import './AssessmentPending.css';

const ASSESSMENT_WRAPPER_KEYS = ['data', 'assessment', 'result', 'assessmentResult', 'aiAssessment'];

function findAssessmentField(payload, fieldNames) {
  if (!payload || typeof payload !== 'object') return undefined;

  for (const fieldName of fieldNames) {
    if (payload[fieldName] != null) return payload[fieldName];
  }

  for (const wrapperKey of ASSESSMENT_WRAPPER_KEYS) {
    const field = findAssessmentField(payload[wrapperKey], fieldNames);
    if (field != null) return field;
  }

  return undefined;
}

/**
 * The assess call (triggered from PhotoUpload) runs the AI model synchronously
 * and returns the full result in one response — there's no separate polling
 * step needed. This screen just displays whatever was handed to it via
 * navigation state.
 *
 * Known MVP gap: if the patient refreshes this page directly, we lose
 * location.state and there's currently no "GET assessment by questionnaire id"
 * endpoint to recover it — only GET /api/assessments/{id}. Worth adding that
 * lookup endpoint before real patients rely on revisiting results.
 */
export default function AssessmentPending() {
  const location = useLocation();
  const navigate = useNavigate();
  const assessment = location.state?.assessment;

  if (!assessment) {
    return (
      <AppShell step={3} totalSteps={3}>
        <ErrorState
          title="We lost track of that result"
          message="Please start a new screening to see your result."
          onRetry={() => navigate('/questionnaire')}
          retryLabel="Start again"
        />
      </AppShell>
    );
  }

  // The endpoint can wrap the AI result (for example in `data` or `result`),
  // and its field names have changed between DTO versions. Resolve both.
  const riskClassification = findAssessmentField(assessment, ['risk_classification', 'aiRiskClassification']);
  const recommendedSpecialist = findAssessmentField(assessment, [
    'recommended_specialist_display_name',
    'recommendedSpecialistDisplayName',
    'recommended_specialist_code',
  ]);
  const patientSummary = findAssessmentField(assessment, ['patientFacingSummary']);

  return (
    <AppShell step={3} totalSteps={3}>
      <PageTransition>
        <div className="screen assessment-result">
          <h1>Your result</h1>
          <p className="assessment-result__subhead">
            This is a preliminary AI read, not a diagnosis. A dentist reviews every case.
          </p>

          <div className="card assessment-result__summary">
            <h3>Patient summary</h3>
            <p>{patientSummary || 'A patient-facing summary was not provided for this assessment.'}</p>
          </div>

          <motion.div
            className="card assessment-result__card"
            initial={{ opacity: 0, scale: 0.96 }}
            animate={{ opacity: 1, scale: 1 }}
            transition={{ duration: 0.3, delay: 0.15, ease: [0.4, 0, 0.2, 1] }}
          >
            <RiskBadge classification={riskClassification} />
          </motion.div>

          {recommendedSpecialist && (
            <div className="card assessment-result__specialist">
              <h3>Suggested specialist</h3>
              <p>{recommendedSpecialist}</p>
            </div>
          )}

          <div className="assessment-result__disclaimer">
            <p>
              This screening is generated by an AI model and reviewed afterward by a dentist.
              It does not replace an in-person examination.
            </p>
          </div>

          <button type="button" className="btn btn-secondary assessment-result__done" onClick={() => navigate('/')}>
            Done
          </button>
        </div>
      </PageTransition>
    </AppShell>
  );
}
